# Generated by Django 4.2.4 on 2023-09-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather_app", "0002_weatherdata_remove_userprofile_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weather_condition", models.CharField(max_length=255)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="WeatherData",
        ),
    ]
